# Generated by Django 4.2.3 on 2023-09-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lilwayneapp', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
